console.log('new project without git')
console.log('new project with git now')
console.log('new project with git 3')
console.log('new project with git 4')
console.log('new project with git 5')
console.log('new project with git now')
console.log('new project with git now')
console.log('new project with git now')
console.log('new project with git now')
console.log('new project with git now')
